version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    environment:
          BUNDLER_VERSION: 2.0.1
# ...

      # Setup bundler 2+
      - run:
          name: setup bundler
          command: |
            gem update --system
            gem uninstall bundler
            rm /usr/local/bin/bundle
            rm /usr/local/bin/bundler
            gem install bundler
    steps:
      - checkout
      - run: echo "hello world"